### ISSUE TITLE
Stretchly Resume Notifications

### ISSUE THREAD

**Issue by s-ahuja** [hovancik/stretchly#374]
Thank you for the great app.

### Prerequisites

- [Yes] I'm using latest version: v 0.19.0

### Description
Can the Stretchly notification + sound alert be disabled for each opening of the mac lid.  

Operating system: Mac OS High Sierra

### Steps to Reproduce

1. Close the lid of Mac
2. Open the lid
3. Stretchly notification shows up

**Expected behavior:** Stretchly to resume, without notification or a checkbox for users to disable it

**Actual behavior:** Notification is shown

**Reproduces how often:** Its a behaviour

### Additional Information
None

**Comment by hovancik** [comment]
Hi, not possible to do right now, but I guess it could be configurable ;] 

You can disable sound in notifications meanwhile, but it's for all notifications.

**Comment by decadent** [comment]
I would remove this notification altogether. The expected behavior is that Stretchly works whenever the system is running and the user is at the computer. This notification only adds a bit of noise to that—there's no point in telling the user that Stretchly is indeed doing its thing.

It looks more like a debugging device, so maybe it should be tied to a debugging flag, or replaced with log messages—if it's still necessary at all.

**Comment by hovancik** [comment]
Yeah I start to agree there should be no notification...

**Comment by sakralbar** [comment]
Some problem with Stretchly 0.20.1 and Linux Mint. The App show resume message after wake-up from suspend.

**Comment by hovancik** [comment]
This has been fixed in #448

**Comment by sakralbar** [comment]
But I still see notifications about the resumption of work, although in the application settings all notifications are turned off.

![2019-10-02_16-20](https://user-images.githubusercontent.com/11180735/66047796-16315200-e531-11e9-82f7-b1054a12f04e.png)

**Comment by hovancik** [comment]
@sakralbar it's only in master, so will go out with next release
